# =============================================================================
# Odoo - Kustomization
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: odoo

resources:
  - configmap.yaml
  - secrets.yaml
  - pvc.yaml
  - deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: odoo
  app.kubernetes.io/part-of: odoo
  app.kubernetes.io/managed-by: argocd
