# =============================================================================
# Kustomization para DNS Records
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sgi-record.yaml

commonLabels:
  app.kubernetes.io/part-of: dns
  app.kubernetes.io/managed-by: argocd
