# =============================================================================
# KUSTOMIZATION - Databases
# =============================================================================
# PostgreSQL y MySQL gen√©ricos para uso compartido
# =============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: databases

resources:
  - namespace.yaml
  - secrets.yaml
  - pvc.yaml
  - postgresql.yaml
  - mysql.yaml

commonLabels:
  app.kubernetes.io/part-of: databases
  app.kubernetes.io/managed-by: argocd
