# =============================================================================
# Kustomization para OpenProject
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - pvc.yaml
  - postgres.yaml
  - deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: openproject
  app.kubernetes.io/managed-by: argocd
