# =============================================================================
# Kustomization para ArgoCD
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - argocd-config.yaml
  - argocd-ingress.yaml

# Para instalar ArgoCD desde el manifest oficial:
# resources:
#   - https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.3/manifests/install.yaml
#   - argocd-config.yaml
#   - argocd-ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
